#!/usr/bin/env bash
# check-commit-parseable.test.sh (shUnit2)
#
# Under test: tools/check-commit-parseable.sh -- the guard that turns "release-please silently
# dropped your commit" into a red job (issue #141).
#
# The script has two halves and they are tested differently on purpose:
#
#   * The SELECTION half -- which commits get judged, which are skipped, and what each outcome
#     means -- is the part with judgement in it, and it is exercised here against real throwaway
#     repositories with an injected verdict command. That needs no node and no network, so it
#     always runs; there is no SKIP path that could quietly disable this file.
#   * The VERDICT half is @conventional-commits/parser, a library. Re-testing a library would only
#     be testing npm. What IS asserted here is the wiring: that the script refuses to answer when
#     the parser is missing, and that CI installs a PINNED version of the right package. Those are
#     the two ways the real parser could stop being consulted without anyone noticing.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
REPO_ROOT="$(cd -- "$TOOLS_DIR/.." && pwd)"
SHUNIT2="$TOOLS_DIR/tests/lib/shunit2"
GUARD="$TOOLS_DIR/check-commit-parseable.sh"
VERDICT_JS="$TOOLS_DIR/check-commit-parseable.js"
WF="$REPO_ROOT/.github/workflows/tests.yml"

# A throwaway repo whose commit subjects are supplied by the caller. The verdict command is
# injected, so which commits are JUDGED is what these cases observe.
make_repo() {
    local dir subject
    dir="$(mktemp -d -t turbo-ccp-XXXXXX)"
    git -C "$dir" init -q
    git -C "$dir" config user.email 'ci@turbo-plugin'
    git -C "$dir" config user.name 'turbo-plugin-ci'
    git -C "$dir" commit -q --allow-empty -m 'base: root'
    for subject in "$@"; do
        git -C "$dir" commit -q --allow-empty -m "$subject"
    done
    printf '%s' "$dir"
}

# Verdict stubs. `always_ok` and `always_bad` stand in for the parser; `always_missing` mimics the
# package not being installed, which the script must treat as "cannot answer", never as a pass.
stub_dir() {
    local dir; dir="$(mktemp -d -t turbo-ccp-stub-XXXXXX)"
    printf '#!/usr/bin/env bash\nexit 0\n'  > "$dir/ok";      chmod +x "$dir/ok"
    printf '#!/usr/bin/env bash\nexit 1\n'  > "$dir/bad";     chmod +x "$dir/bad"
    printf '#!/usr/bin/env bash\nexit 2\n'  > "$dir/missing"; chmod +x "$dir/missing"
    printf '%s' "$dir"
}

run_guard() {
    local repo="$1" verdict="$2"; shift 2
    ( cd "$repo" && TP_COMMIT_PARSE_CMD="$verdict" bash "$GUARD" "$@" >/dev/null 2>&1 )
}

run_guard_output() {
    local repo="$1" verdict="$2"; shift 2
    ( cd "$repo" && TP_COMMIT_PARSE_CMD="$verdict" bash "$GUARD" "$@" 2>&1 )
}

oneTimeSetUp() {
    STUBS="$(stub_dir)"
}
oneTimeTearDown() {
    [ -n "${STUBS:-}" ] && rm -rf "$STUBS"
}

# --- selection ---------------------------------------------------------------------------------

test_an_unparseable_changelog_visible_commit_fails() {
    local repo; repo="$(make_repo 'fix(x): something')"
    run_guard "$repo" "$STUBS/bad" 'HEAD~1..HEAD'
    assertEquals 'an unparseable fix must fail the run' 1 $?
    rm -rf "$repo"
}

test_a_parseable_commit_passes() {
    local repo; repo="$(make_repo 'fix(x): something')"
    run_guard "$repo" "$STUBS/ok" 'HEAD~1..HEAD'
    assertEquals 'a parseable fix must pass' 0 $?
    rm -rf "$repo"
}

# A `chore:` that cannot be parsed costs nothing: its type is configured hidden, so it was never
# going to produce a CHANGELOG entry. Failing on it would be noise that trains people to ignore
# this check.
test_hidden_types_are_not_judged() {
    local repo out
    repo="$(make_repo 'chore: tidy' 'test: add a case' 'ci: bump action' 'build: whatever')"
    run_guard "$repo" "$STUBS/bad" 'HEAD~4..HEAD'
    assertEquals 'hidden types must not fail even when unparseable' 0 $?
    out="$(run_guard_output "$repo" "$STUBS/bad" 'HEAD~4..HEAD')"
    printf '%s' "$out" | grep -q '4 skipped'
    assertTrue "all four should be reported as skipped, got: $out" $?
    rm -rf "$repo"
}

test_all_changelog_visible_types_are_judged() {
    local repo t
    for t in feat fix refactor perf db docs; do
        repo="$(make_repo "$t(x): something")"
        run_guard "$repo" "$STUBS/bad" 'HEAD~1..HEAD'
        assertEquals "type '$t' must be judged" 1 $?
        rm -rf "$repo"
    done
}

# Merge commit subjects are generated by GitHub and are not conventional; judging them would fail
# every PR.
test_merge_commits_are_skipped() {
    local repo; repo="$(make_repo 'fix(x): on a branch')"
    git -C "$repo" checkout -q -b side
    git -C "$repo" commit -q --allow-empty -m 'fix(x): on the side'
    git -C "$repo" checkout -q -
    git -C "$repo" merge -q --no-ff side -m 'Merge pull request #1 from someone/side'
    # The merge itself must not be judged; with an OK verdict for the real commits this passes.
    run_guard "$repo" "$STUBS/ok" 'HEAD~2..HEAD'
    assertEquals 'a merge commit must not be judged' 0 $?
    rm -rf "$repo"
}

# --- refusing to answer ------------------------------------------------------------------------

# The most important case in this file. If the parser is unavailable and the script reported
# success, every commit would sail through and the guard would be worse than useless -- it would
# be a green light with nothing behind it.
test_a_missing_parser_is_never_reported_as_success() {
    local repo; repo="$(make_repo 'fix(x): something')"
    run_guard "$repo" "$STUBS/missing" 'HEAD~1..HEAD'
    assertEquals 'a missing parser must exit 2, not 0 and not 1' 2 $?
    rm -rf "$repo"
}

# An empty range is not evidence. Default is to refuse; --allow-empty is the caller saying it is
# legitimate here.
test_an_empty_range_refuses_by_default() {
    local repo; repo="$(make_repo 'fix(x): something')"
    run_guard "$repo" "$STUBS/ok" 'HEAD..HEAD'
    assertEquals 'an empty range must not be a silent pass' 2 $?
    run_guard "$repo" "$STUBS/ok" --allow-empty 'HEAD..HEAD'
    assertEquals 'an empty range passes only when the caller allows it' 0 $?
    rm -rf "$repo"
}

# --- wiring ------------------------------------------------------------------------------------

test_the_verdict_half_exists_and_requires_the_real_parser() {
    assertTrue "verdict script missing: $VERDICT_JS" "[ -s '$VERDICT_JS' ]"
    grep -q "@conventional-commits/parser" "$VERDICT_JS"
    assertTrue 'the verdict half must consult the parser release-please uses' $?
}

# A floating version could disagree with what release-please resolves, which would make this check
# answer a question nobody asked -- in either direction.
test_ci_installs_a_pinned_parser() {
    local line
    line="$(grep -E 'npm install .*@conventional-commits/parser' "$WF" | head -1)"
    assertNotEquals 'the workflow must install the parser' '' "$line"
    printf '%s' "$line" | grep -qE '@conventional-commits/parser@[0-9]+\.[0-9]+\.[0-9]+'
    assertTrue "the installed parser must be pinned to an exact version, got: $line" $?
}

test_the_workflow_actually_runs_this_guard() {
    grep -q 'tools/check-commit-parseable.sh' "$WF"
    assertTrue 'tests.yml must invoke the guard' $?
}

# A range git cannot resolve is a broken caller, not an empty one. Collapsing the two -- which
# `git rev-list ... || true` does -- lets --allow-empty wave a broken invocation through as a clean
# run. The all-zero `before` GitHub sends on branch creation is exactly such a range, and it lands
# on the one path that passes --allow-empty.
test_an_unresolvable_range_is_refused_even_with_allow_empty() {
    local repo; repo="$(make_repo 'fix(x): something')"
    run_guard "$repo" "$STUBS/ok" --allow-empty '0000000000000000000000000000000000000000..HEAD'
    assertEquals 'an unresolvable range must exit 2 even with --allow-empty' 2 $?
    rm -rf "$repo"
}

# Selection must err towards ASKING. `fix:no-space` is not valid conventional-commits, so
# release-please drops it -- but an exact-shape filter files it as "not a visible type" and never
# judges it, which is this script's own failure mode relocated from the verdict to the selection.
test_a_malformed_visible_type_is_still_judged() {
    local repo; repo="$(make_repo 'fix:no space after the colon')"
    run_guard "$repo" "$STUBS/bad" 'HEAD~1..HEAD'
    assertEquals 'a malformed but clearly-typed subject must reach the parser' 1 $?
    rm -rf "$repo"
}

# ...without becoming so loose that unrelated subjects get judged.
test_lookalike_subjects_are_not_judged() {
    local repo s
    for s in 'fixup! earlier commit' 'perfectly fine prose' 'dbg: scratch note' 'documentation rewrite'; do
        repo="$(make_repo "$s")"
        run_guard "$repo" "$STUBS/bad" 'HEAD~1..HEAD'
        assertEquals "subject '$s' must NOT be judged" 0 $?
        rm -rf "$repo"
    done
}

# The job must do real work on every declared trigger. With steps gated on event_name, a trigger
# nobody wired up means both steps skip, no step fails, and the job reports success having judged
# nothing -- green because it did nothing, which is the failure this job exists to stop.
test_every_workflow_trigger_is_covered_by_a_step() {
    local triggers trig conditions missing='' count=0
    # Trigger names: two-space indent inside the `on:` block.
    triggers="$(awk '
        /^on:[[:space:]]*$/ { inon = 1; next }
        inon && /^[a-z]/    { inon = 0 }
        inon && /^  [a-z_]+:[[:space:]]*$/ { gsub(/[ :]/, "", $0); print }
    ' "$WF")"
    # Every `if:` on a step of this job, joined.
    conditions="$(awk '
        /^  commit-messages-parseable:/ { injob = 1; next }
        injob && /^  [a-z]/ { injob = 0 }
        injob && /if:/ { print }
    ' "$WF" | tr '\n' ' ')"

    for trig in $triggers; do
        count=$((count + 1))
        # Covered either by being named in a condition, or by a catch-all `!=` condition.
        case "$conditions" in
            *"$trig"*) ;;
            *'!='*)    ;;
            *) missing="$missing $trig" ;;
        esac
    done
    assertTrue "expected to find the workflow's triggers, found $count" "[ '$count' -ge 2 ]"
    assertEquals "triggers with no step that runs for them:$missing" '' "$missing"
    # And the catch-all must exist, otherwise a future trigger silently skips every step.
    printf '%s' "$conditions" | grep -q '!='
    assertTrue 'the job needs a catch-all step so an unlisted trigger cannot no-op' $?
}

# shellcheck source=/dev/null
. "$SHUNIT2"
