param(
    [string]$Pubxml = '',
    [string]$Configuration = '',
    [string]$Platform = '',
    [string]$Project = '',
    [string]$RepoRoot = '',
    # Extra MSBuild properties, each `Name=Value`, appended after everything this script builds.
    # PowerShell: -MsBuildProperty A=1,B=2 . Bash: --msbuild-property A=1,B=2 (the delegate passes
    # one argument through, so comma-separate rather than repeating the flag). A property value
    # containing a comma is therefore not expressible -- no MSBuild property this is needed for has
    # one, and the alternative is a quoting scheme nobody would get right on the first try.
    #
    # Why this exists: publish had no way at all to pass one extra property, so the only workaround
    # for anything the script does not model was to abandon the plugin and hand-run MSBuild -- which
    # also loses the frontend pack, the resolved-target report and the publish-location output
    # (issue #45). Appended LAST on purpose: MSBuild takes the final value, so a caller can override
    # something the script computed rather than being blocked by it.
    [string[]]$MsBuildProperty = @()
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. ([System.IO.Path]::Combine($PSScriptRoot, 'lib', 'Common.ps1'))

try {
    Probe-GitVersion

    $repoRoot = Resolve-DotnetRepoRoot -RepoRoot $RepoRoot

    # Target: explicit CLI arg → config.toml [publish].project (no auto-detect). publish needs a
    # .csproj (reads PublishProfiles / publishes one project); a .sln is rejected (no -AllowSolution).
    $target = Resolve-ProjectTarget -RepoRoot $repoRoot -Section 'publish' -CliProjectValue $Project
    $projectFile = $target.Path

    # MSBuild path: config.local.toml [tools] msbuild_path → standard VS install locations
    # (strict cut, no env var fallback — throws pointing at config.local.toml if missing)
    $msbuildPath = Find-MSBuild -RepoRoot $repoRoot

    # pubxml: CLI arg → config.toml [publish].default_pubxml → auto-detect single .pubxml under project's Properties/PublishProfiles
    $pubxmlPathRaw = Resolve-ConfigValue -RepoRoot $repoRoot -Section 'publish' -Key 'default_pubxml' -CliValue $Pubxml -Default $null
    if ([string]::IsNullOrWhiteSpace($pubxmlPathRaw)) {
        $projectDir = [System.IO.Path]::GetDirectoryName($projectFile)
        $profilesDir = Join-Path $projectDir 'Properties/PublishProfiles'
        $pubxmls = @()
        if (Test-Path -LiteralPath $profilesDir -PathType Container) {
            $pubxmls = @(Get-ChildItem -LiteralPath $profilesDir -Filter '*.pubxml' -ErrorAction SilentlyContinue)
        }
        if ($pubxmls.Count -eq 0) {
            throw 'No .pubxml found. Specify -Pubxml or set [publish].default_pubxml in .turbo-plugin/config.toml.'
        }
        if ($pubxmls.Count -gt 1) {
            $names = ($pubxmls | ForEach-Object { $_.Name }) -join ', '
            throw "Multiple .pubxml files found under $profilesDir ($names). Specify -Pubxml or set [publish].default_pubxml."
        }
        $pubxmlAbsPath = $pubxmls[0].FullName
    } else {
        $pubxmlAbsPath = Resolve-RepoPath -RepoRoot $repoRoot -PathValue $pubxmlPathRaw
    }
    if (-not (Test-Path -LiteralPath $pubxmlAbsPath -PathType Leaf)) {
        throw "Publish profile does not exist: $pubxmlAbsPath"
    }

    # Configuration / Platform: agent value first (it always wins), then the pubxml.
    #
    # The "just omit /p:Configuration and let the profile govern" assumption that used to live here
    # is WRONG for publish, disproved on a real machine 2026-07-31: publishing a Release profile via
    # /p:PublishProfile produced a DEBUG build (/optimize-, DEBUG constant, sources from obj\Debug\)
    # dropped into bin\Release\Publish. With /p:PublishProfile the profile's <Configuration> does not
    # reach the BUILD -- the csproj's own `<Configuration Condition="...">Debug</Configuration>`
    # default wins -- so the profile has to be read here and passed explicitly.
    #
    # Do NOT "restore" the omit behaviour by copying it back from Build-Web.ps1: omitting is correct
    # for build (MSBuild / .sln / Directory.Build.props decide, which is what VS does) and wrong for
    # publish.
    #
    # Each value falls back through TWO pubxml element names, because Visual Studio does not write
    # the ones you would expect. A FileSystem profile generated by VS carries
    # <LastUsedBuildConfiguration> / <LastUsedPlatform> and frequently has no <Configuration> /
    # <Platform> at all -- so reading only the latter found nothing and publish silently fell back
    # to the csproj default of Debug|AnyCPU, i.e. the exact opposite of what the user had selected
    # in VS (issue #51). <Configuration> is still tried first: when a profile does define it, it is
    # the deliberate value, whereas LastUsed* only records what happened to run last.
    #
    # Platform now has a fallback too. The previous comment here said it was "deliberately left
    # alone -- no evidence it misbehaves"; issue #51 is that evidence. AnyCPU built a dependent
    # class library as MSIL against AMD64 interop assemblies, and precompilation then died in
    # ASPNETCOMPILER with a BadImageFormatException.
    #
    # /p:Platform is NOT interchangeable with /p:PlatformTarget, so do not "simplify" to the latter:
    # measured on the same project, PlatformTarget=x64 silenced the MSB3270 architecture warning but
    # precompilation still failed, while Platform=x64 succeeded. They select different intermediate
    # directories (obj\Release\ vs obj\x64\Release\) and therefore different build paths.
    $publishConfiguration = Resolve-ConfigValue -RepoRoot $repoRoot -Section 'publish' -Key 'configuration' -CliValue $Configuration -Default $null
    if ([string]::IsNullOrWhiteSpace($publishConfiguration)) {
        $publishConfiguration = Get-MsbuildProperty -Path $pubxmlAbsPath -Name 'Configuration'
    }
    if ([string]::IsNullOrWhiteSpace($publishConfiguration)) {
        $publishConfiguration = Get-MsbuildProperty -Path $pubxmlAbsPath -Name 'LastUsedBuildConfiguration'
    }
    $publishPlatform = Resolve-ConfigValue -RepoRoot $repoRoot -Section 'publish' -Key 'platform' -CliValue $Platform -Default $null
    if ([string]::IsNullOrWhiteSpace($publishPlatform)) {
        $publishPlatform = Get-MsbuildProperty -Path $pubxmlAbsPath -Name 'Platform'
    }
    if ([string]::IsNullOrWhiteSpace($publishPlatform)) {
        $publishPlatform = Get-MsbuildProperty -Path $pubxmlAbsPath -Name 'LastUsedPlatform'
    }

    # Read [frontend] dir for the result template. Publish is the costlier place for a silently
    # skipped frontend pack: the output can reach a deployed environment, so "was the frontend
    # packed?" must be stated, not left to a stdout line nobody relays (issue #30).
    $frontendDir = Resolve-FrontendPackDir -RepoRoot $repoRoot

    # Pre-publish: run Compress-Content for frontend. Compress-Content.ps1 is shipped in this
    # plugin alongside Publish-Web.ps1, so the prior Test-Path guard was redundant —
    # Compress-Content already exits 0 with a skip message when [frontend] isn't configured.
    & ([System.IO.Path]::Combine($PSScriptRoot, 'Compress-Content.ps1')) -RepoRoot $repoRoot
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    $publishProfileName = [System.IO.Path]::GetFileNameWithoutExtension($pubxmlAbsPath)
    $publishProfileDir  = [System.IO.Path]::GetDirectoryName($pubxmlAbsPath)

    Write-Output "Running MSBuild Publish for $projectFile"
    Write-Output "  Publish profile: $publishProfileName"
    Write-Output "  Profile root:    $publishProfileDir"

    # SolutionDir for a csproj target, same as Build-Web does: publish only ever takes a csproj, and
    # the packages.config `<HintPath>..\packages\...` convention is anchored on the solution / repo
    # root rather than the project directory.
    $solutionDir = $repoRoot.TrimEnd('\') + '\'

    # /restore + /p:RestorePackagesConfig=true, matching Build-Web (see there for why /restore has to
    # stay the switch form and what RestorePackagesConfig buys). Publish needs them in its own right:
    # /p:DeployOnBuild=true means this invocation BUILDS the project, and the publish SKILL never
    # requires a build first — so publish can legitimately be the first command run on a fresh clone.
    # Without restore here, a packages.config project fails on first publish.
    #
    # /p:Configuration carries the agent's value or, failing that, the pubxml's (resolved above).
    # /p:Platform is passed only when the agent supplied one.
    $publishArgs = @(
        $projectFile,
        '/restore',
        '/p:RestorePackagesConfig=true',
        "/p:SolutionDir=$solutionDir",
        '/p:DeployOnBuild=true',
        "/p:PublishProfile=$publishProfileName",
        "/p:PublishProfileRootFolder=$publishProfileDir"
    )
    if (-not [string]::IsNullOrWhiteSpace($publishConfiguration)) { $publishArgs += "/p:Configuration=$publishConfiguration" }
    if (-not [string]::IsNullOrWhiteSpace($publishPlatform)) { $publishArgs += "/p:Platform=$publishPlatform" }

    # Caller-supplied properties go last so they win (see the -MsBuildProperty comment above).
    # Validated rather than pasted through: a typo like "AspnetCompilerPath" with no '=' would
    # otherwise reach MSBuild as a bare argument, where it is interpreted as a PROJECT FILE to
    # build. The resulting error talks about a missing project and never mentions the property.
    # The comma split happens HERE, not in parameter binding. Called in-process, PowerShell would
    # split `-MsBuildProperty A=1,B=2` into two elements by itself -- but every real caller reaches
    # this script through `powershell.exe -File`, and that path hands the whole thing over as one
    # string. Splitting in the script is what makes the .ps1 and .sh entry points behave the same;
    # relying on binding produced a literal `/p:A=1,B=2` argument (caught by its own test).
    foreach ($entry in $MsBuildProperty) {
        if ([string]::IsNullOrWhiteSpace($entry)) { continue }
        foreach ($property in ($entry -split ',')) {
            if ([string]::IsNullOrWhiteSpace($property)) { continue }
            $trimmed = $property.Trim()
            if ($trimmed -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') {
                throw "Invalid -MsBuildProperty entry: '$trimmed'. Expected Name=Value (e.g. AspnetCompilerPath=`$(MSBuildFrameworkToolsPath64)); separate multiple properties with commas."
            }
            $publishArgs += "/p:$trimmed"
        }
    }

    # Echo the whole command line — same reasoning as Build-Web: what the script did has to be
    # readable from stdout, or an agent diagnosing a failure will guess at it.
    Write-Output "  MSBuild args: $($publishArgs -join ' ')"
    & $msbuildPath @publishArgs

    # Backstop only: under EAP=Stop a real MSBuild failure that writes stderr throws a terminating
    # NativeCommandError BEFORE this line (caught by the outer catch -> exit 1, still fail-loud). This
    # guard only catches the rare non-zero-exit-without-stderr case. Working-as-designed per repo
    # CLAUDE.md ("PS 5.1 相容性" — EAP=Stop + native-exe stderr); do not "fix" by forcing reachability.
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Write-Output 'Publish succeeded.'

    # Parse via Select-Xml (avoids PS 5.1 + StrictMode + outer-try interaction that
    # caused [xml] cast / New-Object XmlDocument to silently coerce to String here).
    $publishUrlNodes = $null
    $methodNodes = $null
    try {
        # VS-generated pubxml uses camelCase <publishUrl> (and PascalCase <WebPublishMethod>);
        # local-name() is case-sensitive, so query both shapes via translate() lowercase-match.
        $publishUrlNodes = @(Select-Xml -Path $pubxmlAbsPath -XPath "//*[translate(local-name(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')='publishurl']" | ForEach-Object { $_.Node })
        $methodNodes     = @(Select-Xml -Path $pubxmlAbsPath -XPath "//*[translate(local-name(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz')='webpublishmethod']" | ForEach-Object { $_.Node })
    } catch {
        [Console]::Error.WriteLine("Warning: failed to parse publish profile XML; output path unknown. ($($_.Exception.Message))")
        return
    }

    $method = if ($methodNodes.Count -gt 0) { $methodNodes[$methodNodes.Count - 1].InnerText.Trim() } else { '' }
    if ([string]::IsNullOrWhiteSpace($method)) { $method = 'FileSystem' }
    Write-Output "Method: $method"

    if ($publishUrlNodes.Count -eq 0) {
        [Console]::Error.WriteLine('Warning: <PublishUrl> not found in profile; output path unknown.')
        return
    }

    $publishUrlRaw = $publishUrlNodes[$publishUrlNodes.Count - 1].InnerText.Trim()
    if ([string]::IsNullOrWhiteSpace($publishUrlRaw)) {
        [Console]::Error.WriteLine('Warning: <PublishUrl> is empty; output path unknown.')
        return
    }

    # The result-template lead lines (the 糾錯閘) shared by every PUBLISH_OUTPUT branch:
    # Target = the csproj actually resolved/published, Profile = the pubxml used. They sit above the
    # bare path/URL line(s) so the agent relays "which project" the same way build/run/stop do
    # (Format-*ResultLines / KTD5), while the path/URL lines stay bare for terminal clickability.
    # The relay instruction says "fenced code block", NOT "bare": the agent's reply is rendered as
    # markdown, where '\' followed by ASCII punctuation is an escape sequence and the backslash is
    # eaten. A Windows path loses exactly one separator before every hidden directory
    # (...\.claude\... -> ....claude\...), which reads as a typo rather than as corruption. A code
    # block is not rendered, so the path survives verbatim AND stays on its own selectable line.
    $publishMarker = 'PUBLISH_OUTPUT (relay these lines to the user as the publish result, inside a fenced code block so the path is not mangled by markdown):'
    $publishLead   = @("Target: $projectFile", "Profile: $publishProfileName", (Format-FrontendStatusLine -FrontendDir $frontendDir))

    if ($publishUrlRaw -match '\$\(') {
        [Console]::Error.WriteLine('Warning: <PublishUrl> contains MSBuild properties; cannot resolve statically.')
        # Unresolved MSBuild property — no real path computable; relay the raw PublishUrl as the
        # location line after the shared lead, via the SAME marker so the SKILL parses one shape.
        Write-Output $publishMarker
        foreach ($l in $publishLead) { Write-Output $l }
        Write-Output $publishUrlRaw
        return
    }

    $projectDir = [System.IO.Path]::GetDirectoryName($projectFile)
    $out = Get-PublishOutputLines -PublishUrlRaw $publishUrlRaw -Method $method -ProjectDir $projectDir

    # KTD8: after the shared marker + lead lines, emit the publish location as BARE
    # line(s) the agent relays VERBATIM — the raw Windows path then the file:/// URL (FileSystem),
    # each on its own line with NO trailing punctuation, so the terminal keeps the paths clickable.
    Write-Output $publishMarker
    foreach ($l in $publishLead) { Write-Output $l }
    if ($out.IsFileSystem) {
        Write-Output $out.Resolved
        Write-Output $out.DisplayPath
    } else {
        Write-Output $out.Resolved
    }
}
catch {
    [Console]::Error.WriteLine($_.Exception.Message)
    exit 1
}
