#!/usr/bin/env bash
# check-commit-parseable.sh -- fail loudly on a commit release-please would silently drop.
#
# The problem (issue #141). release-please decides what goes in a CHANGELOG by parsing each commit
# with @conventional-commits/parser, a STRICT PEG grammar. When that parser rejects a message,
# release-please logs one line -- `commit could not be parsed: <sha> <subject>` -- and moves on.
# Not an error, not a warning. The commit's CHANGELOG entry simply never appears, and the commit
# does not count towards the version bump either, so a plugin whose only releasable commit in a
# cycle is unparseable does not get released at all while the Release PR looks perfectly normal.
#
# It has already happened: 11 commits across this repo's history lost their bullet this way, all
# to the same construct -- a '(' left open across a line break in the message body. Nothing local
# can warn you, because commitlint and friends use the LENIENT regex parser, which accepts it.
#
# So this check exists to turn a silent omission into a red job. Usage:
#
#   tools/check-commit-parseable.sh <git-range>      e.g. origin/main...HEAD
#
# Only commits whose type would produce a CHANGELOG entry are judged; a `chore:` that cannot be
# parsed costs nothing because it was never going to appear. Merge commits are skipped: their
# subject is generated by GitHub and is not conventional.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

# Types that map to a visible CHANGELOG section in release-please-config.json. `chore`, `test`,
# `ci` and `build` are configured hidden, so losing one of those is harmless.
VISIBLE_TYPES='feat|fix|refactor|perf|db|docs'

# The verdict command. Overridable ONLY so the unit tests can exercise the selection logic without
# a node install; CI and humans get the real parser.
PARSE_CMD="${TP_COMMIT_PARSE_CMD:-node "$SCRIPT_DIR/check-commit-parseable.js"}"

usage() {
    echo "usage: $(basename "$0") [--allow-empty] <git-range>" >&2
    echo "  e.g. $(basename "$0") origin/main...HEAD" >&2
    echo "  --allow-empty: treat a range with no commits as a pass instead of an error." >&2
}

ALLOW_EMPTY=0
if [ "${1:-}" = '--allow-empty' ]; then
    ALLOW_EMPTY=1
    shift
fi

if [ "$#" -ne 1 ]; then
    usage
    exit 2
fi
RANGE="$1"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "check-commit-parseable: not inside a git work tree" >&2
    exit 2
fi

shas="$(git rev-list --no-merges "$RANGE" 2>/dev/null || true)"
if [ -z "$shas" ]; then
    # An empty range is not evidence of anything, so the DEFAULT is to refuse: a range that
    # silently resolves to nothing is precisely how a check becomes a no-op that still shows green
    # -- the failure mode this whole script exists to prevent. Whether empty is legitimate depends
    # on the caller, so the caller says. A pull request always has at least one commit, so empty
    # there means the range is wrong; a push can legitimately carry no non-merge commits.
    if [ "$ALLOW_EMPTY" -eq 1 ]; then
        echo "check-commit-parseable: range '$RANGE' has no non-merge commits; nothing to check (--allow-empty)."
        exit 0
    fi
    echo "check-commit-parseable: range '$RANGE' contains no non-merge commits; nothing to check." >&2
    echo "  If that is unexpected, the range is wrong -- this is NOT a pass." >&2
    echo "  Pass --allow-empty if an empty range is legitimate for this caller." >&2
    exit 2
fi

tmp="$(mktemp -d 2>/dev/null || mktemp -d -t tpccp)"
# shellcheck disable=SC2064
trap "rm -rf '$tmp'" EXIT

checked=0
skipped=0
bad=0

while IFS= read -r sha; do
    [ -n "$sha" ] || continue
    subject="$(git log -1 --format='%s' "$sha")"
    if ! printf '%s' "$subject" | grep -qE "^($VISIBLE_TYPES)(\([^)]*\))?!?: "; then
        skipped=$((skipped + 1))
        continue
    fi
    checked=$((checked + 1))
    git log -1 --format='%B' "$sha" > "$tmp/msg"
    # Capture the verdict's REAL exit code. `if ! cmd; then rc=$?` would set rc from the negation,
    # not from cmd -- so exit 2 (parser missing) would arrive here looking like exit 1 (bad
    # commit), and the run would blame a perfectly good commit for a broken toolchain. Measured
    # while building this: that is exactly what happened.
    set +e
    $PARSE_CMD "$tmp/msg"
    rc=$?
    set -e
    if [ "$rc" -eq 2 ]; then
        echo "check-commit-parseable: the parser could not run; refusing to report success." >&2
        exit 2
    fi
    if [ "$rc" -ne 0 ]; then
        bad=$((bad + 1))
        echo "  ^ ${sha:0:8}  $subject" >&2
        echo >&2
    fi
done <<EOF
$shas
EOF

if [ "$bad" -ne 0 ]; then
    cat >&2 <<'MSG'
check-commit-parseable: FAILED

release-please would silently drop the commit(s) above: no CHANGELOG entry, and no contribution to
the version bump. Nothing in the release run would say so.

Fix the commit message and force-push, e.g. `git rebase -i` and reword. The usual cause is a '('
opened on one line and closed on the next -- keep it on one line, or use a dash or [square
brackets] instead. Square and angle brackets are fine across line breaks; only parentheses are not.
MSG
    exit 1
fi

echo "check-commit-parseable: OK -- $checked changelog-visible commit(s) parse; $skipped skipped (hidden type)."
